local var0 = nil
local var5 = x % y % z
local var10 = x % y % z
local var15 = x % y % z
local var20 = x / y % z
local var25 = x * y % z
local var30 = x % y * z
local var35 = x % y / z
local var40 = x + y % z
local var45 = (x + y) % z
local var50 = x % y - z
local var55 = x % (y - z)
local var60 = x % y ^ z
local var65 = (x % y) ^ z
local var70 = x ^ y % z
local var75 = x ^ (y % z)
